CREATE DATABASE IF NOT EXISTS DEFAULT_DB;

USE DEFAULT_DB;

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    role VARCHAR(15) NOT NULL,
    password VARCHAR(500) NOT NULL
);