CREATE DATABASE IF NOT EXISTS DEFAULT_DB;

USE DEFAULT_DB;

CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    role VARCHAR(15) NOT NULL,
    password VARCHAR(500) NOT NULL,
    firstName VARCHAR(50) NOT NULL DEFAULT '',
    lastName VARCHAR(50) NOT NULL DEFAULT '',
    phone VARCHAR(15) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS messages (
	idMsg INT PRIMARY KEY AUTO_INCREMENT,
	idRcv INT,
    idSnd INT,
    messageContent VARCHAR(500) NOT NULL,
    msgTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    msgRead BOOL NOT NULL DEFAULT false
);